### ISSUE TITLE
Figure out and fix broken Travis Build

### ISSUE THREAD

**Issue by codeZeilen** [HPI-SWA-Teaching/Koans#1]
So far I could not reproduce it locally but will investigate tomorrow.

**Comment by codeZeilen** [comment]
This was an annoying one to fix. It turned out to be a race condition between the test and some I/O to the changes file. It did not occur when running in headful mode, probably because it slowed down the test execution. The current solution is not perfect but fixes it. ( @fniephaus This might be relevant for smalltalkCi)

**Comment by krono** [comment]
Can you tag the sha?

**Comment by fniephaus** [comment]
https://github.com/HPI-SWA-Teaching/Koans/commit/7b75a3944c6f0d12ed81b4f9ac306276340b3d10
